version: "3.9"

services:
  backend:
    image: maven:3.9-eclipse-temurin-21
    container_name: finpref-backend
    working_dir: /app
    command: >
      sh -lc "
        mvn -q -DskipTests dependency:go-offline &&
        mvn -q spring-boot:run
      "
    # 若用 application.yml 的預設，就把下一行 env_file 移除
    env_file: .env
    environment:
      MAVEN_OPTS: "-Xms256m -Xmx1024m"
      # 需要 profile 再開：
      # SPRING_PROFILES_ACTIVE: dev
    volumes:
      - ./backend:/app
      - maven-repo:/root/.m2
    ports:
      - "8080:8080"
    networks:
      - appnet
    restart: unless-stopped

  frontend:
    image: node:20-alpine
    container_name: finpref-frontend
    working_dir: /app
    command: sh -c "if [ -f package-lock.json ]; then npm ci; else npm i; fi && npm run dev -- --host 0.0.0.0 --port ${VITE_PORT:-5173}"
    env_file: .env
    ports:
      - "${VITE_PORT:-5173}:${VITE_PORT:-5173}"           # Vite
      - "${VITE_HMR_PORT:-24678}:${VITE_HMR_PORT:-24678}" # HMR WS
    environment:
      VITE_PROXY_TARGET: http://backend:8080
      CHOKIDAR_USEPOLLING: "${CHOKIDAR_USEPOLLING:-true}"
    volumes:
      - ./frontend:/app
    depends_on:
      - backend
    networks:
      - appnet
    restart: unless-stopped

networks:
  appnet:

volumes:
  maven-repo:
